apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-sample-app
spec:
  template:
    spec:
      containers:
        - name: go-sample-app
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 4
            periodSeconds: 3
          readinessProbe:
            initialDelaySeconds: 4
            periodSeconds: 10
            httpGet:
              path: /
              port: 8080
