apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: go-sample-app
  name: go-sample-app
  namespace: dev
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-sample-app
  type: ClusterIP
status:
  loadBalancer: {}
